# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Architecte d'intérieur
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Le site d'un architecte d'intérieur
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.architecte.fr" # the base hostname & protocol for your site
twitter_username: archicool
github_username: archichouette

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 3000

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
