# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Architecte d'intérieur
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Le site d'un architecte d'intérieur
baseurl: "/la-poupee-russe" # the subpath of your site, e.g. /blog
url: "http://www.architecte.fr" # the base hostname & protocol for your site
twitter_username: archicool
github_username: archichouette

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 3000

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Pagination
paginate: 5

# Image Tags
image:
  source: images/_fullsize
  output: generated
  presets:
    list:
      width: 720
      height: 720
    cover:
      width: 1920
    col-12: 
      width: 1280
      attr:
        class: "col-sm-12"
    col-10:
      attr:
        class: "col-sm-10 col-sm-offset-1 col-xs-12"
      width: 750
    col-6:
      attr:
        class: "col-sm-6 col-sm-offset-3 col-xs-12"
      width: 500
    users:
      attr:
        class: author-portrait
        itemprop: image
      width: 350
